CREATE TABLE [dbo].[TB_FMS_AccCat] (
    [AccID] INT NULL,
    [CatID] INT NULL,
    [ID]    INT IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_TB_FMS_AccCat] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__TB_FMS_Ac__AccID__114A936A] FOREIGN KEY ([AccID]) REFERENCES [dbo].[TB_FMS_Account] ([AccID]),
    CONSTRAINT [FK__TB_FMS_Ac__CatID__123EB7A3] FOREIGN KEY ([CatID]) REFERENCES [dbo].[TB_FMS_Category] ([CatID])
);

